# Generated by Django 5.0.4 on 2024-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=1000)),
                ('attendents', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GoodMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=1000)),
                ('attendents', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
